'use client'

// Ambient atmosphere — survey-map contour rings at the left/right margins
// plus Claude-style warm blobs that breathe in the corners. The rings are
// organic closed paths (NOT perfect circles), each generated by perturbing
// a base radius with several sine harmonics, so they read as topographic
// contour lines being slowly traced. The middle of the viewport stays
// clean; decoration lives in the gutters.
//
// Motion is pure CSS keyframes — slow rotate on the ring groups, slow
// breathe on the blobs — so prefers-reduced-motion (handled in globals.css)
// turns the whole atmosphere off without any JS branching.

// ─── Contour path generation ──────────────────────────────────────────
// Build a closed organic ring in a 100×100 viewBox. Layered sine waves
// at incommensurate frequencies make the contour wobble irregularly
// around its base radius without ever exactly repeating.
function contourRing(baseR: number, variation: number, seed: number) {
  const points = 96
  const parts: string[] = []
  for (let i = 0; i <= points; i++) {
    const a = (i / points) * Math.PI * 2
    const r =
      baseR +
      Math.sin(a * 3 + seed * 1.10) * variation * 0.50 +
      Math.sin(a * 5 + seed * 1.73) * variation * 0.30 +
      Math.sin(a * 8 + seed * 2.31) * variation * 0.20 +
      Math.sin(a * 13 + seed * 3.07) * variation * 0.12
    const x = 50 + r * Math.cos(a)
    const y = 50 + r * Math.sin(a)
    parts.push(`${i === 0 ? 'M' : 'L'} ${x.toFixed(2)} ${y.toFixed(2)}`)
  }
  parts.push('Z')
  return parts.join(' ')
}

// Open hand-drawn-looking curve from (x1,y1) to (x2,y2) with sinuous
// wobble that fades to zero at both ends. Used for stray surveyor
// scribbles in the corners.
function handDrawn(
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  amp: number,
  seed: number,
) {
  const points = 48
  const dx = x2 - x1
  const dy = y2 - y1
  const len = Math.hypot(dx, dy) || 1
  const px = -dy / len
  const py = dx / len
  const parts: string[] = []
  for (let i = 0; i <= points; i++) {
    const t = i / points
    const bx = x1 + dx * t
    const by = y1 + dy * t
    const wobble =
      Math.sin(t * Math.PI * 4 + seed) * amp * 0.50 +
      Math.sin(t * Math.PI * 7 + seed * 1.6) * amp * 0.28 +
      Math.sin(t * Math.PI * 11 + seed * 2.3) * amp * 0.14
    const envelope = Math.sin(t * Math.PI) // 0 at ends, 1 at middle
    const x = bx + px * wobble * envelope
    const y = by + py * wobble * envelope
    parts.push(`${i === 0 ? 'M' : 'L'} ${x.toFixed(2)} ${y.toFixed(2)}`)
  }
  return parts.join(' ')
}

// Pre-generate the ring sets so the paths are stable across renders.
const LEFT_RINGS = [
  { d: contourRing(30, 2.4, 1.3), opacity: 0.32 },
  { d: contourRing(38, 2.8, 4.1), opacity: 0.26 },
  { d: contourRing(46, 3.0, 6.9), opacity: 0.20 },
  { d: contourRing(54, 3.2, 9.5), opacity: 0.14 },
  { d: contourRing(62, 3.4, 12.7), opacity: 0.10 },
]

const RIGHT_RINGS = [
  { d: contourRing(30, 2.6, 21.3), opacity: 0.28 },
  { d: contourRing(38, 2.6, 24.1), opacity: 0.23 },
  { d: contourRing(46, 2.9, 26.9), opacity: 0.18 },
  { d: contourRing(54, 3.1, 29.5), opacity: 0.13 },
  { d: contourRing(62, 3.4, 32.7), opacity: 0.09 },
]

// Stray hand-drawn scribbles. (x1,y1)→(x2,y2) in 100×100 user units.
const TOP_LEFT_SCRIBBLES = [
  { d: handDrawn(2, 18, 28, 6, 1.4, 1.7), opacity: 0.26 },
  { d: handDrawn(6, 32, 22, 24, 0.9, 3.4), opacity: 0.20 },
]
const BOTTOM_RIGHT_SCRIBBLES = [
  { d: handDrawn(72, 88, 98, 78, 1.6, 5.1), opacity: 0.24 },
  { d: handDrawn(78, 96, 94, 92, 0.8, 7.2), opacity: 0.19 },
]

export default function AtmosphereBackground() {
  return (
    <div
      aria-hidden
      className="pointer-events-none fixed inset-0 overflow-hidden"
      style={{ zIndex: 0 }}
    >
      {/* Left edge: terracotta contour rings, slowly rotating clockwise.
          SVG center is pulled 78% past the left edge so the inner rings
          stay off-screen and only the outer arcs lean into the gutter. */}
      <svg
        className="absolute left-0 top-1/2"
        style={{
          width: 'min(125vh, 1300px)',
          height: 'min(125vh, 1300px)',
          transform: 'translate(-78%, -50%)',
        }}
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid meet"
      >
        <g className="atmosphere-ring atmosphere-ring--cw">
          {LEFT_RINGS.map((ring, i) => (
            <path
              key={`l-${i}`}
              d={ring.d}
              fill="none"
              stroke="rgba(180, 90, 60, 1)"
              strokeOpacity={ring.opacity}
              strokeWidth="0.28"
              strokeLinejoin="round"
              strokeLinecap="round"
            />
          ))}
        </g>
      </svg>

      {/* Right edge: sage contour rings, slowly rotating counterclockwise.
          Pulled 78% past the right edge for the same gutter-only effect. */}
      <svg
        className="absolute right-0 top-1/2"
        style={{
          width: 'min(125vh, 1300px)',
          height: 'min(125vh, 1300px)',
          transform: 'translate(78%, -50%)',
        }}
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid meet"
      >
        <g className="atmosphere-ring atmosphere-ring--ccw">
          {RIGHT_RINGS.map((ring, i) => (
            <path
              key={`r-${i}`}
              d={ring.d}
              fill="none"
              stroke="rgba(107, 122, 78, 1)"
              strokeOpacity={ring.opacity}
              strokeWidth="0.28"
              strokeLinejoin="round"
              strokeLinecap="round"
            />
          ))}
        </g>
      </svg>

      {/* Hand-drawn surveyor scribbles in two opposite corners. */}
      <svg
        className="absolute left-0 top-0"
        style={{ width: 'min(46vw, 520px)', height: 'min(46vw, 520px)' }}
        viewBox="0 0 100 100"
        preserveAspectRatio="xMinYMin meet"
      >
        {TOP_LEFT_SCRIBBLES.map((c, i) => (
          <path
            key={`tl-${i}`}
            d={c.d}
            fill="none"
            stroke="rgba(180, 90, 60, 1)"
            strokeOpacity={c.opacity}
            strokeWidth="0.40"
            strokeLinejoin="round"
            strokeLinecap="round"
          />
        ))}
      </svg>

      <svg
        className="absolute right-0 bottom-0"
        style={{ width: 'min(46vw, 520px)', height: 'min(46vw, 520px)' }}
        viewBox="0 0 100 100"
        preserveAspectRatio="xMaxYMax meet"
      >
        {BOTTOM_RIGHT_SCRIBBLES.map((c, i) => (
          <path
            key={`br-${i}`}
            d={c.d}
            fill="none"
            stroke="rgba(107, 122, 78, 1)"
            strokeOpacity={c.opacity}
            strokeWidth="0.40"
            strokeLinejoin="round"
            strokeLinecap="round"
          />
        ))}
      </svg>

      {/* Claude-style warm blobs in corners — soft radial gradients that
          breathe. They reinforce the edge decoration without competing
          with content in the middle of the viewport. */}
      <div
        className="atmosphere-blob atmosphere-blob--1 absolute -left-32 -top-32 h-[460px] w-[460px] rounded-full"
        style={{
          background:
            'radial-gradient(circle, rgba(180, 90, 60, 0.13) 0%, rgba(180, 90, 60, 0) 65%)',
        }}
      />
      <div
        className="atmosphere-blob atmosphere-blob--2 absolute -right-40 top-1/4 h-[520px] w-[520px] rounded-full"
        style={{
          background:
            'radial-gradient(circle, rgba(181, 138, 58, 0.10) 0%, rgba(181, 138, 58, 0) 65%)',
        }}
      />
      <div
        className="atmosphere-blob atmosphere-blob--3 absolute -bottom-40 left-1/4 h-[500px] w-[500px] rounded-full"
        style={{
          background:
            'radial-gradient(circle, rgba(107, 122, 78, 0.10) 0%, rgba(107, 122, 78, 0) 65%)',
        }}
      />
      <div
        className="atmosphere-blob atmosphere-blob--4 absolute -bottom-32 -right-32 h-[440px] w-[440px] rounded-full"
        style={{
          background:
            'radial-gradient(circle, rgba(180, 90, 60, 0.09) 0%, rgba(180, 90, 60, 0) 65%)',
        }}
      />
    </div>
  )
}
