'use client'

// Ambient atmosphere — survey-map contour rings at the left/right margins
// plus Claude-style warm blobs that breathe in the corners. The rings are
// organic closed paths (NOT perfect circles), each generated by perturbing
// a base radius with several sine harmonics, so they read as topographic
// contour lines being slowly traced. The middle of the viewport stays
// clean; decoration lives in the gutters.
//
// Motion is pure CSS keyframes — slow rotate on the ring groups, slow
// breathe on the blobs — so prefers-reduced-motion (handled in globals.css)
// turns the whole atmosphere off without any JS branching.

// Open hand-drawn-looking curve from (x1,y1) to (x2,y2) with sinuous
// wobble that fades to zero at both ends. Used for stray surveyor
// scribbles in the corners.
function handDrawn(
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  amp: number,
  seed: number,
) {
  const points = 48
  const dx = x2 - x1
  const dy = y2 - y1
  const len = Math.hypot(dx, dy) || 1
  const px = -dy / len
  const py = dx / len
  const parts: string[] = []
  for (let i = 0; i <= points; i++) {
    const t = i / points
    const bx = x1 + dx * t
    const by = y1 + dy * t
    const wobble =
      Math.sin(t * Math.PI * 4 + seed) * amp * 0.50 +
      Math.sin(t * Math.PI * 7 + seed * 1.6) * amp * 0.28 +
      Math.sin(t * Math.PI * 11 + seed * 2.3) * amp * 0.14
    const envelope = Math.sin(t * Math.PI) // 0 at ends, 1 at middle
    const x = bx + px * wobble * envelope
    const y = by + py * wobble * envelope
    parts.push(`${i === 0 ? 'M' : 'L'} ${x.toFixed(2)} ${y.toFixed(2)}`)
  }
  return parts.join(' ')
}

// Concentric ring sets — clean perfect circles centered at (50, 50) of
// the SVG viewBox. The SVG itself is translated 78% past the viewport
// edge, so only the outer arcs of these rings lean into the gutter,
// reading as a rippling-out-from-the-side gradient of rings rather
// than the abstract lobed shapes that came before.
type RingSpec = { r: number; opacity: number }
const LEFT_RINGS: RingSpec[] = [
  { r: 30, opacity: 0.42 },
  { r: 37, opacity: 0.36 },
  { r: 44, opacity: 0.30 },
  { r: 51, opacity: 0.24 },
  { r: 58, opacity: 0.18 },
  { r: 65, opacity: 0.13 },
  { r: 72, opacity: 0.08 },
]

const RIGHT_RINGS: RingSpec[] = [
  { r: 30, opacity: 0.36 },
  { r: 37, opacity: 0.31 },
  { r: 44, opacity: 0.26 },
  { r: 51, opacity: 0.21 },
  { r: 58, opacity: 0.16 },
  { r: 65, opacity: 0.11 },
  { r: 72, opacity: 0.07 },
]

// Stray hand-drawn scribbles. (x1,y1)→(x2,y2) in 100×100 user units.
const TOP_LEFT_SCRIBBLES = [
  { d: handDrawn(2, 18, 28, 6, 1.4, 1.7), opacity: 0.26 },
  { d: handDrawn(6, 32, 22, 24, 0.9, 3.4), opacity: 0.20 },
]
const BOTTOM_RIGHT_SCRIBBLES = [
  { d: handDrawn(72, 88, 98, 78, 1.6, 5.1), opacity: 0.24 },
  { d: handDrawn(78, 96, 94, 92, 0.8, 7.2), opacity: 0.19 },
]

export default function AtmosphereBackground() {
  return (
    <div
      aria-hidden
      className="pointer-events-none fixed inset-0 overflow-hidden"
      style={{ zIndex: 0 }}
    >
      {/* Left edge: terracotta contour rings, slowly rotating clockwise.
          SVG center is pulled 78% past the left edge so the inner rings
          stay off-screen and only the outer arcs lean into the gutter. */}
      <svg
        className="absolute left-0 top-1/2"
        style={{
          width: 'min(125vh, 1300px)',
          height: 'min(125vh, 1300px)',
          transform: 'translate(-78%, -50%)',
        }}
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid meet"
      >
        <g className="atmosphere-ring atmosphere-ring--cw">
          {LEFT_RINGS.map((ring, i) => (
            <circle
              key={`l-${i}`}
              cx="50"
              cy="50"
              r={ring.r}
              fill="none"
              stroke="rgba(180, 90, 60, 1)"
              strokeOpacity={ring.opacity}
              strokeWidth="0.22"
            />
          ))}
        </g>
      </svg>

      {/* Right edge: sage contour rings, slowly rotating counterclockwise.
          Pulled 78% past the right edge for the same gutter-only effect. */}
      <svg
        className="absolute right-0 top-1/2"
        style={{
          width: 'min(125vh, 1300px)',
          height: 'min(125vh, 1300px)',
          transform: 'translate(78%, -50%)',
        }}
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid meet"
      >
        <g className="atmosphere-ring atmosphere-ring--ccw">
          {RIGHT_RINGS.map((ring, i) => (
            <circle
              key={`r-${i}`}
              cx="50"
              cy="50"
              r={ring.r}
              fill="none"
              stroke="rgba(107, 122, 78, 1)"
              strokeOpacity={ring.opacity}
              strokeWidth="0.22"
            />
          ))}
        </g>
      </svg>

      {/* Hand-drawn surveyor scribbles in two opposite corners. */}
      <svg
        className="absolute left-0 top-0"
        style={{ width: 'min(46vw, 520px)', height: 'min(46vw, 520px)' }}
        viewBox="0 0 100 100"
        preserveAspectRatio="xMinYMin meet"
      >
        {TOP_LEFT_SCRIBBLES.map((c, i) => (
          <path
            key={`tl-${i}`}
            d={c.d}
            fill="none"
            stroke="rgba(180, 90, 60, 1)"
            strokeOpacity={c.opacity}
            strokeWidth="0.40"
            strokeLinejoin="round"
            strokeLinecap="round"
          />
        ))}
      </svg>

      <svg
        className="absolute right-0 bottom-0"
        style={{ width: 'min(46vw, 520px)', height: 'min(46vw, 520px)' }}
        viewBox="0 0 100 100"
        preserveAspectRatio="xMaxYMax meet"
      >
        {BOTTOM_RIGHT_SCRIBBLES.map((c, i) => (
          <path
            key={`br-${i}`}
            d={c.d}
            fill="none"
            stroke="rgba(107, 122, 78, 1)"
            strokeOpacity={c.opacity}
            strokeWidth="0.40"
            strokeLinejoin="round"
            strokeLinecap="round"
          />
        ))}
      </svg>

      {/* Claude-style warm blobs in corners — soft radial gradients that
          breathe. They reinforce the edge decoration without competing
          with content in the middle of the viewport. */}
      <div
        className="atmosphere-blob atmosphere-blob--1 absolute -left-32 -top-32 h-[460px] w-[460px] rounded-full"
        style={{
          background:
            'radial-gradient(circle, rgba(180, 90, 60, 0.13) 0%, rgba(180, 90, 60, 0) 65%)',
        }}
      />
      <div
        className="atmosphere-blob atmosphere-blob--2 absolute -right-40 top-1/4 h-[520px] w-[520px] rounded-full"
        style={{
          background:
            'radial-gradient(circle, rgba(181, 138, 58, 0.10) 0%, rgba(181, 138, 58, 0) 65%)',
        }}
      />
      <div
        className="atmosphere-blob atmosphere-blob--3 absolute -bottom-40 left-1/4 h-[500px] w-[500px] rounded-full"
        style={{
          background:
            'radial-gradient(circle, rgba(107, 122, 78, 0.10) 0%, rgba(107, 122, 78, 0) 65%)',
        }}
      />
      <div
        className="atmosphere-blob atmosphere-blob--4 absolute -bottom-32 -right-32 h-[440px] w-[440px] rounded-full"
        style={{
          background:
            'radial-gradient(circle, rgba(180, 90, 60, 0.09) 0%, rgba(180, 90, 60, 0) 65%)',
        }}
      />
    </div>
  )
}
