'use client'

import { useEffect, useId, useState } from 'react'

// Renders a Mermaid diagram client-side. Mermaid is loaded via dynamic import
// so it stays out of the initial bundle for routes that don't use it.
export default function Mermaid({ chart }: { chart: string }) {
  const reactId = useId().replace(/[^a-zA-Z0-9]/g, '_')
  const [svg, setSvg] = useState<string | null>(null)
  const [err, setErr] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false

    ;(async () => {
      try {
        const m = await import('mermaid')
        const mermaid = m.default

        mermaid.initialize({
          startOnLoad: false,
          theme: 'base',
          securityLevel: 'loose',
          fontFamily:
            'ui-monospace, SFMono-Regular, Menlo, Monaco, "JetBrains Mono", monospace',
          themeVariables: {
            // Surfaces
            background: '#0a0a0b',
            primaryColor: '#0c0c10',
            primaryTextColor: '#fafafa',
            primaryBorderColor: 'rgba(255,255,255,0.16)',

            // Lines + edges
            lineColor: 'rgba(255,255,255,0.32)',
            edgeLabelBackground: '#0a0a0b',

            // Accent (matches indigo design token)
            secondaryColor: 'rgba(129,140,248,0.10)',
            secondaryBorderColor: 'rgba(129,140,248,0.45)',
            secondaryTextColor: '#fafafa',
            tertiaryColor: '#0c0c10',
            tertiaryBorderColor: 'rgba(255,255,255,0.10)',
            tertiaryTextColor: '#a1a1aa',

            // Cluster (subgraph) backgrounds
            clusterBkg: 'rgba(255,255,255,0.02)',
            clusterBorder: 'rgba(255,255,255,0.10)',

            // Text
            textColor: '#e4e4e7',
            mainBkg: '#0c0c10',
            nodeBorder: 'rgba(255,255,255,0.18)',

            // Sequence diagrams
            actorBkg: '#0c0c10',
            actorBorder: 'rgba(129,140,248,0.45)',
            actorTextColor: '#fafafa',
            actorLineColor: 'rgba(255,255,255,0.30)',
            signalColor: 'rgba(255,255,255,0.65)',
            signalTextColor: '#e4e4e7',
            labelBoxBkgColor: '#0c0c10',
            labelBoxBorderColor: 'rgba(129,140,248,0.45)',
            labelTextColor: '#fafafa',
            loopTextColor: '#a1a1aa',
            noteBkgColor: 'rgba(129,140,248,0.10)',
            noteBorderColor: 'rgba(129,140,248,0.30)',
            noteTextColor: '#e4e4e7',

            // ER / state
            attributeBackgroundColorOdd: '#0c0c10',
            attributeBackgroundColorEven: 'rgba(255,255,255,0.02)',
          },
          flowchart: {
            curve: 'basis',
            padding: 14,
            useMaxWidth: true,
          },
          sequence: {
            useMaxWidth: true,
            actorMargin: 60,
          },
        })

        const id = `mmd_${reactId}`
        const { svg } = await mermaid.render(id, chart)
        if (!cancelled) setSvg(svg)
      } catch (e) {
        if (!cancelled) {
          const msg = e instanceof Error ? e.message : 'Diagram render failed.'
          setErr(msg)
        }
      }
    })()

    return () => {
      cancelled = true
    }
  }, [chart, reactId])

  return (
    <figure className="mermaid-block my-9 overflow-hidden rounded-xl border border-hairline bg-surface-1">
      <div className="border-b border-hairline px-4 py-2 font-mono text-[10.5px] uppercase tracking-eyebrow text-zinc-500">
        diagram
      </div>
      <div className="overflow-x-auto p-5 md:p-7">
        {svg ? (
          <div
            className="mermaid-rendered flex justify-center"
            // SVG is generated by mermaid, which we trust.
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        ) : err ? (
          <pre className="whitespace-pre-wrap font-mono text-[12px] text-red-400">
            {err}
          </pre>
        ) : (
          <div className="grid h-32 place-items-center font-mono text-[11px] uppercase tracking-eyebrow text-zinc-600">
            rendering diagram…
          </div>
        )}
      </div>
    </figure>
  )
}
